language: c

sudo: false

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: c1BEcWGUMERYBFDkkVC28rHQQtLOz508FToM5IX/rDlvRU/CTMZhok4QmZfvJhQIs1jC6vIka4KZf+6Uibkn1D7BIP3fAorUTSOa3Sw3qT99jnGFNu5SB+0huUx1CxtT8StjmA00k8Hq7qmmVF4sW8UxdxBeGQ0rF47knbSf6HU=

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended

install:
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

cache:
  directories:
  - $HOME/R

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - export R_VIGNETTE=formatR.html
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
