language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    - secure: c1BEcWGUMERYBFDkkVC28rHQQtLOz508FToM5IX/rDlvRU/CTMZhok4QmZfvJhQIs1jC6vIka4KZf+6Uibkn1D7BIP3fAorUTSOa3Sw3qT99jnGFNu5SB+0huUx1CxtT8StjmA00k8Hq7qmmVF4sW8UxdxBeGQ0rF47knbSf6HU=

repos:
  XRAN: http://yihui.name/xran

before_install:
  - "wget -q http://yihui.name/xran/.gitconfig -O ~/.gitconfig"

after_success:
  - export R_VIGNETTE=formatR.html
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
